using configs in /home/ubuntu/.mrjob.conf
creating tmp directory /tmp/Stations_Statistics.ubuntu.20140519.000217.492145
writing to /tmp/Stations_Statistics.ubuntu.20140519.000217.492145/step-0-mapper_part-00000
Counters from step 1:
  MRWeather:
    total in map_one: 9358395
writing to /tmp/Stations_Statistics.ubuntu.20140519.000217.492145/step-0-mapper-sorted
> sort /tmp/Stations_Statistics.ubuntu.20140519.000217.492145/step-0-mapper_part-00000
Piping files into sort for Windows compatibility
> sort
Traceback (most recent call last):
  File "/home/ubuntu/UCSD_BigData/notebooks/weather.mapreduce/Stations_Statistics.py", line 88, in <module>
    MRWeather.run()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/job.py", line 494, in run
    mr_job.execute()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/job.py", line 512, in execute
    super(MRJob, self).execute()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/launch.py", line 147, in execute
    self.run_job()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/launch.py", line 208, in run_job
    runner.run()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/runner.py", line 458, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/sim.py", line 191, in _run
    self._invoke_sort(self._step_input_paths(), sort_output_path)
  File "/usr/local/lib/python2.7/dist-packages/mrjob/runner.py", line 1225, in _invoke_sort
    proc.stdin.write(buf)
IOError: [Errno 32] Broken pipe
